name = "aegis-initiative-proxy"
main = "index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "aegisinitiative.com/*", zone_name = "aegisinitiative.com" },
  { pattern = "www.aegisinitiative.com/*", zone_name = "aegisinitiative.com" }
]
